export const seedDatabase = () => ({
    clients: [
        {
            id: "c1",
            company: "Harbor & Pine Holdings",
            contact: "Elena Voss",
            email: "elena@harborpine.com",
            phone: "(206) 555-0142",
            city: "Seattle",
            since: "2022-04-11",
        },
        {
            id: "c2",
            company: "Cedar School District",
            contact: "Marcus Hale",
            email: "m.hale@cedarsd.edu",
            phone: "(253) 555-0190",
            city: "Tacoma",
            since: "2023-01-18",
        },
        {
            id: "c3",
            company: "Westline Logistics",
            contact: "Priya Shah",
            email: "priya@westline.co",
            phone: "(206) 555-0177",
            city: "Kent",
            since: "2024-08-02",
        },
        {
            id: "c4",
            company: "Oak & Pine Health",
            contact: "Jonah Abebe",
            email: "j.abebe@oakpine.health",
            phone: "(425) 555-0114",
            city: "Bellevue",
            since: "2023-09-27",
        },
        {
            id: "c5",
            company: "Seattle Waterfront Office",
            contact: "Nora Blake",
            email: "nora.blake@seattle.gov",
            phone: "(206) 555-0166",
            city: "Seattle",
            since: "2021-06-09",
        },
    ],
    projects: [
        {
            id: "p1",
            name: "Harbor Point Residences",
            code: "HP-240",
            clientId: "c1",
            location: "Alki, Seattle",
            status: "active",
            progress: 68,
            budget: 18400000,
            spent: 11240000,
            startDate: "2025-03-03",
            endDate: "2026-11-20",
            manager: "Luis Ortega",
        },
        {
            id: "p2",
            name: "Cedar Ridge School",
            code: "CR-118",
            clientId: "c2",
            location: "South Tacoma",
            status: "active",
            progress: 41,
            budget: 9200000,
            spent: 3480000,
            startDate: "2025-09-15",
            endDate: "2027-02-28",
            manager: "Amina Farouk",
        },
        {
            id: "p3",
            name: "Westline Warehouse",
            code: "WW-077",
            clientId: "c3",
            location: "Kent Valley",
            status: "planning",
            progress: 12,
            budget: 6400000,
            spent: 410000,
            startDate: "2026-04-06",
            endDate: "2027-01-15",
            manager: "Chris Daley",
        },
        {
            id: "p4",
            name: "Oak & Pine Clinic",
            code: "OP-054",
            clientId: "c4",
            location: "Bellevue",
            status: "on-hold",
            progress: 55,
            budget: 5100000,
            spent: 2760000,
            startDate: "2025-06-02",
            endDate: "2026-08-30",
            manager: "Helen Cho",
        },
        {
            id: "p5",
            name: "Pier 9 Retrofit",
            code: "P9-301",
            clientId: "c5",
            location: "Elliott Bay",
            status: "active",
            progress: 83,
            budget: 12750000,
            spent: 10980000,
            startDate: "2024-11-12",
            endDate: "2026-06-18",
            manager: "Luis Ortega",
        },
        {
            id: "p6",
            name: "Maple Court Townhomes",
            code: "MC-016",
            clientId: "c1",
            location: "Redmond",
            status: "complete",
            progress: 100,
            budget: 4300000,
            spent: 4210000,
            startDate: "2024-02-20",
            endDate: "2025-12-12",
            manager: "Helen Cho",
        },
    ],
    crew: [
        { id: "w1", name: "Luis Ortega", role: "Superintendent", trade: "General", projectId: "p1", phone: "(206) 555-2201", status: "on-site", hourlyRate: 68 },
        { id: "w2", name: "Amina Farouk", role: "Superintendent", trade: "General", projectId: "p2", phone: "(253) 555-2208", status: "on-site", hourlyRate: 66 },
        { id: "w3", name: "Diego Marquez", role: "Foreman", trade: "Carpentry", projectId: "p1", phone: "(206) 555-2214", status: "on-site", hourlyRate: 52 },
        { id: "w4", name: "Ruth Nguyen", role: "Journeyman", trade: "Electrical", projectId: "p5", phone: "(206) 555-2230", status: "on-site", hourlyRate: 58 },
        { id: "w5", name: "Samir Patel", role: "Operator", trade: "Heavy equipment", projectId: "p2", phone: "(253) 555-2242", status: "on-site", hourlyRate: 49 },
        { id: "w6", name: "Ivy Brooks", role: "Foreman", trade: "Ironwork", projectId: "p5", phone: "(206) 555-2255", status: "leave", hourlyRate: 54 },
        { id: "w7", name: "Owen Blake", role: "Journeyman", trade: "Plumbing", projectId: "p4", phone: "(425) 555-2261", status: "off", hourlyRate: 51 },
        { id: "w8", name: "Helen Cho", role: "Project manager", trade: "General", projectId: "p4", phone: "(425) 555-2274", status: "off", hourlyRate: 72 },
        { id: "w9", name: "Chris Daley", role: "Project manager", trade: "General", projectId: "p3", phone: "(206) 555-2288", status: "on-site", hourlyRate: 70 },
        { id: "w10", name: "Nora Iqbal", role: "Apprentice", trade: "Carpentry", projectId: "p1", phone: "(206) 555-2293", status: "on-site", hourlyRate: 28 },
    ],
    equipment: [
        { id: "e1", name: "Tower crane TC-4", type: "Crane", projectId: "p1", status: "in-use", dailyRate: 1850, hours: 940 },
        { id: "e2", name: "CAT 320 excavator", type: "Earthwork", projectId: "p2", status: "in-use", dailyRate: 720, hours: 610 },
        { id: "e3", name: "JLG 600S boom", type: "Lift", projectId: "p5", status: "in-use", dailyRate: 410, hours: 288 },
        { id: "e4", name: "Telehandler TH-12", type: "Lift", projectId: "p1", status: "available", dailyRate: 340, hours: 1204 },
        { id: "e5", name: "Concrete pump 32m", type: "Concrete", projectId: "p5", status: "maintenance", dailyRate: 960, hours: 770 },
        { id: "e6", name: "Skid steer S70", type: "Earthwork", projectId: "p3", status: "available", dailyRate: 260, hours: 1540 },
        { id: "e7", name: "120kW generator", type: "Power", projectId: "p2", status: "in-use", dailyRate: 180, hours: 860 },
        { id: "e8", name: "Scissor lift 26ft", type: "Lift", projectId: "p4", status: "maintenance", dailyRate: 145, hours: 430 },
    ],
    materials: [
        { id: "m1", name: "Rebar #5", unit: "tons", onHand: 18, reorderAt: 24, projectId: "p1", supplier: "Puget Steel", unitCost: 980 },
        { id: "m2", name: "3/4 plywood", unit: "sheets", onHand: 64, reorderAt: 80, projectId: "p1", supplier: "Cascade Lumber", unitCost: 42 },
        { id: "m3", name: "Ready-mix 4000 psi", unit: "yd³", onHand: 46, reorderAt: 20, projectId: "p5", supplier: "Bay Cement", unitCost: 168 },
        { id: "m4", name: "Copper pipe 3/4", unit: "lengths", onHand: 30, reorderAt: 40, projectId: "p4", supplier: "North Plumbing Supply", unitCost: 36 },
        { id: "m5", name: "EMT conduit 1in", unit: "lengths", onHand: 120, reorderAt: 50, projectId: "p2", supplier: "Sound Electric", unitCost: 11 },
        { id: "m6", name: "Structural bolts A325", unit: "boxes", onHand: 9, reorderAt: 12, projectId: "p5", supplier: "Puget Steel", unitCost: 74 },
        { id: "m7", name: "Gypsum board 5/8", unit: "sheets", onHand: 210, reorderAt: 80, projectId: "p2", supplier: "Cascade Lumber", unitCost: 16 },
        { id: "m8", name: "Roofing membrane", unit: "rolls", onHand: 6, reorderAt: 8, projectId: "p3", supplier: "Rainier Roofing", unitCost: 220 },
    ],
    invoices: [
        { id: "i1", number: "INV-1042", clientId: "c1", projectId: "p1", amount: 860000, status: "paid", issued: "2026-08-01", due: "2026-08-31" },
        { id: "i2", number: "INV-1048", clientId: "c2", projectId: "p2", amount: 240000, status: "sent", issued: "2026-09-12", due: "2026-10-12" },
        { id: "i3", number: "INV-1051", clientId: "c3", projectId: "p3", amount: 90000, status: "draft", issued: "2026-09-28", due: "2026-10-28" },
        { id: "i4", number: "INV-1055", clientId: "c4", projectId: "p4", amount: 180000, status: "overdue", issued: "2026-08-04", due: "2026-09-04" },
        { id: "i5", number: "INV-1060", clientId: "c5", projectId: "p5", amount: 410000, status: "sent", issued: "2026-09-20", due: "2026-10-20" },
        { id: "i6", number: "INV-1062", clientId: "c1", projectId: "p6", amount: 125000, status: "paid", issued: "2025-12-02", due: "2026-01-02" },
        { id: "i7", number: "INV-1066", clientId: "c1", projectId: "p1", amount: 540000, status: "sent", issued: "2026-09-30", due: "2026-10-30" },
    ],
    logs: [
        { id: "l1", projectId: "p1", date: "2026-10-01", weather: "Clear, 63°F", crewCount: 42, summary: "Level 6 slab pour finished before noon. Crane held the east facade panels until 3.", author: "Luis Ortega" },
        { id: "l2", projectId: "p5", date: "2026-10-01", weather: "Wind 18 mph", crewCount: 27, summary: "Deck welding paused after 11 because of wind. Electrical rough-in continued below deck.", author: "Ruth Nguyen" },
        { id: "l3", projectId: "p2", date: "2026-09-30", weather: "Light rain", crewCount: 31, summary: "Foundation waterproofing on the north wing. Excavator moved spoils to the east stockpile.", author: "Amina Farouk" },
        { id: "l4", projectId: "p4", date: "2026-09-18", weather: "Overcast", crewCount: 6, summary: "Site secured while the owner reviews the imaging-room change order. No production work.", author: "Helen Cho" },
        { id: "l5", projectId: "p1", date: "2026-09-29", weather: "Clear, 66°F", crewCount: 39, summary: "Rebar delivery short two tons. Carpentry stayed on the west balcony forms.", author: "Diego Marquez" },
        { id: "l6", projectId: "p3", date: "2026-09-26", weather: "Dry", crewCount: 8, summary: "Layout stakes set for the truck court. Waiting on the building permit stamp.", author: "Chris Daley" },
    ],
});
